<?php
$conexao = mysqli_connect('nspro16.hostgator.com.br', 'calbus59_se6ry68', '!$Gd2*7AP&aP', 'calbus59_ctpuzzle_old');

if (!$conexao) {
    die('Could not connect: ' . mysqli_error($conexao));
}
file_put_contents("teste.txt",print_r($_POST,true));

$sql="INSERT INTO resultadosNovos ";
$sql.= "(dataHora, aluno, pontosGeral0, pontosDica0, pontosClicks0, pontosTempo0, pontosLimpar0, pontosPulou0, pontosGeral1,pontosDica1, pontosClicks1, pontosTempo1, pontosLimpar1, pontosPulou1, pontosGeral2, pontosDica2, pontosClicks2, pontosTempo2, pontosLimpar2, pontosPulou2, pontosGeral3, pontosDica3, pontosClicks3, pontosTempo3, pontosLimpar3, pontosPulou3, matchGeral0, matchDica0, matchClicks0, matchTempo0, matchGiros0, matchPulou0, matchGeral1, matchDica1, matchClicks1, matchTempo1, matchGiros1, matchPulou1, tangramGeral0, tangramDica0, tangramClicks0, tangramTempo0, tangramGiros0, tangramPulou0, tangramGeral1, tangramDica1, tangramClicks1, tangramTempo1, tangramGiros1, tangramPulou1, classificaGeral,classificaTempo, classificaDica, classificaTentativa, classificaLimpar, classificaPulou, sequenciaGeral0, sequenciaTempo0, sequenciaDica0, sequenciaTentativa0, sequenciaPulou0, sequenciaGeral1, sequenciaTempo1, sequenciaDica1, sequenciaTentativa1, sequenciaPulou1, progGeral0, progTempo0, progInstrucoes0, progApagou0, progApagouAll0, progPlay0, progPulou0, progGeral1, progTempo1, progInstrucoes1, progApagou1, progApagouAll1, progPlay1, progPulou1, progGeral2, progTempo2, progInstrucoes2, progApagou2, progApagouAll2, progPlay2, progPulou2, progGeral3, progTempo3, progInstrucoes3, progApagou3, progApagouAll3, progPlay3, progPulou3, progGeral4, progTempo4, progInstrucoes4, progApagou4, progApagouAll4, progPlay4, progPulou4, progGeral5, progTempo5, progInstrucoes5, progApagou5, progApagouAll5, progPlay5, progPulou5, progGeral6, progTempo6, progInstrucoes6, progApagou6, progApagouAll6, progPlay6, progPulou6, progLoopGeral0, progTempoLoop0, progInstrucoesLoop0, progApagouLoop0, progApagouAllLoop0, progPlayLoop0, progLoopLoop0, progInstrucoesLoopLoop0, progPulouLoop0, progLoopGeral1, progTempoLoop1, progInstrucoesLoop1, progApagouLoop1, progApagouAllLoop1, progPlayLoop1, progLoopLoop1, progInstrucoesLoopLoop1, progPulouLoop1, abstracao, decomposicao, reconhecimento, algoritmo) ";
$sql.= "VALUES ";
$sql.= "('".($_POST['dataHora'])."'";
$sql.= ", '".($_POST['aluno'])."'";
$sql.= ", ".($_POST['pontosGeral0']);
$sql.= ", ".($_POST['pontosDica0']);
$sql.= ", ".($_POST['pontosClicks0']);
$sql.= ", ".($_POST['pontosTempo0']);
$sql.= ", ".($_POST['pontosLimpar0']);
$sql.= ", ".($_POST['pontosPulou0']);
$sql.= ", ".($_POST['pontosGeral1']);
$sql.= ", ".($_POST['pontosDica1']);
$sql.= ", ".($_POST['pontosClicks1']);
$sql.= ", ".($_POST['pontosTempo1']);
$sql.= ", ".($_POST['pontosLimpar1']);
$sql.= ", ".($_POST['pontosPulou1']);
$sql.= ", ".($_POST['pontosGeral2']);
$sql.= ", ".($_POST['pontosDica2']);
$sql.= ", ".($_POST['pontosClicks2']);
$sql.= ", ".($_POST['pontosTempo2']);
$sql.= ", ".($_POST['pontosLimpar2']);
$sql.= ", ".($_POST['pontosPulou2']);
$sql.= ", ".($_POST['pontosGeral3']);
$sql.= ", ".($_POST['pontosDica3']);
$sql.= ", ".($_POST['pontosClicks3']);
$sql.= ", ".($_POST['pontosTempo3']);
$sql.= ", ".($_POST['pontosLimpar3']);
$sql.= ", ".($_POST['pontosPulou3']);
$sql.= ", ".($_POST['matchGeral0']);
$sql.= ", ".($_POST['matchDica0']);
$sql.= ", ".($_POST['matchClicks0']);
$sql.= ", ".($_POST['matchTempo0']);
$sql.= ", ".($_POST['matchGiros0']);
$sql.= ", ".($_POST['matchPulou0']);
$sql.= ", ".($_POST['matchGeral1']);
$sql.= ", ".($_POST['matchDica1']);
$sql.= ", ".($_POST['matchClicks1']);
$sql.= ", ".($_POST['matchTempo1']);
$sql.= ", ".($_POST['matchGiros1']);
$sql.= ", ".($_POST['matchPulou1']);
$sql.= ", ".($_POST['tangramGeral0']);
$sql.= ", ".($_POST['tangramDica0']);
$sql.= ", ".($_POST['tangramClicks0']);
$sql.= ", ".($_POST['tangramTempo0']);
$sql.= ", ".($_POST['tangramGiros0']);
$sql.= ", ".($_POST['tangramPulou0']);
$sql.= ", ".($_POST['tangramGeral1']);
$sql.= ", ".($_POST['tangramDica1']);
$sql.= ", ".($_POST['tangramClicks1']);
$sql.= ", ".($_POST['tangramTempo1']);
$sql.= ", ".($_POST['tangramGiros1']);
$sql.= ", ".($_POST['tangramPulou1']);
$sql.= ", ".($_POST['classificaGeral']);
$sql.= ", ".($_POST['classificaTempo']);
$sql.= ", ".($_POST['classificaDica']);
$sql.= ", ".($_POST['classificaTentativa']);
$sql.= ", ".($_POST['classificaLimpar']);
$sql.= ", ".($_POST['classificaPulou']);
$sql.= ", ".($_POST['sequenciaGeral0']);
$sql.= ", ".($_POST['sequenciaTempo0']);
$sql.= ", ".($_POST['sequenciaDica0']);
$sql.= ", ".($_POST['sequenciaTentativa0']);
$sql.= ", ".($_POST['sequenciaPulou0']);
$sql.= ", ".($_POST['sequenciaGeral1']);
$sql.= ", ".($_POST['sequenciaTempo1']);
$sql.= ", ".($_POST['sequenciaDica1']);
$sql.= ", ".($_POST['sequenciaTentativa1']);
$sql.= ", ".($_POST['sequenciaPulou1']);
$sql.= ", ".($_POST['progGeral0']);
$sql.= ", ".($_POST['progTempo0']);
$sql.= ", ".($_POST['progInstrucoes0']);
$sql.= ", ".($_POST['progApagou0']);
$sql.= ", ".($_POST['progApagouAll0']);
$sql.= ", ".($_POST['progPlay0']);
$sql.= ", ".($_POST['progPulou0']);
$sql.= ", ".($_POST['progGeral1']);
$sql.= ", ".($_POST['progTempo1']);
$sql.= ", ".($_POST['progInstrucoes1']);
$sql.= ", ".($_POST['progApagou1']);
$sql.= ", ".($_POST['progApagouAll1']);
$sql.= ", ".($_POST['progPlay1']);
$sql.= ", ".($_POST['progPulou1']);
$sql.= ", ".($_POST['progGeral2']);
$sql.= ", ".($_POST['progTempo2']);
$sql.= ", ".($_POST['progInstrucoes2']);
$sql.= ", ".($_POST['progApagou2']);
$sql.= ", ".($_POST['progApagouAll2']);
$sql.= ", ".($_POST['progPlay2']);
$sql.= ", ".($_POST['progPulou2']);
$sql.= ", ".($_POST['progGeral3']);
$sql.= ", ".($_POST['progTempo3']);
$sql.= ", ".($_POST['progInstrucoes3']);
$sql.= ", ".($_POST['progApagou3']);
$sql.= ", ".($_POST['progApagouAll3']);
$sql.= ", ".($_POST['progPlay3']);
$sql.= ", ".($_POST['progPulou3']);
$sql.= ", ".($_POST['progGeral4']);
$sql.= ", ".($_POST['progTempo4']);
$sql.= ", ".($_POST['progInstrucoes4']);
$sql.= ", ".($_POST['progApagou4']);
$sql.= ", ".($_POST['progApagouAll4']);
$sql.= ", ".($_POST['progPlay4']);
$sql.= ", ".($_POST['progPulou4']);
$sql.= ", ".($_POST['progGeral5']);
$sql.= ", ".($_POST['progTempo5']);
$sql.= ", ".($_POST['progInstrucoes5']);
$sql.= ", ".($_POST['progApagou5']);
$sql.= ", ".($_POST['progApagouAll5']);
$sql.= ", ".($_POST['progPlay5']);
$sql.= ", ".($_POST['progPulou5']);
$sql.= ", ".($_POST['progGeral6']);
$sql.= ", ".($_POST['progTempo6']);
$sql.= ", ".($_POST['progInstrucoes6']);
$sql.= ", ".($_POST['progApagou6']);
$sql.= ", ".($_POST['progApagouAll6']);
$sql.= ", ".($_POST['progPlay6']);
$sql.= ", ".($_POST['progPulou6']);
$sql.= ", ".($_POST['progLoopGeral0']);
$sql.= ", ".($_POST['progTempoLoop0']);
$sql.= ", ".($_POST['progInstrucoesLoop0']);
$sql.= ", ".($_POST['progApagouLoop0']);
$sql.= ", ".($_POST['progApagouAllLoop0']);
$sql.= ", ".($_POST['progPlayLoop0']);
$sql.= ", ".($_POST['progLoopLoop0']);
$sql.= ", ".($_POST['progInstrucoesLoopLoop0']);
$sql.= ", ".($_POST['progPulouLoop0']);
$sql.= ", ".($_POST['progLoopGeral1']);
$sql.= ", ".($_POST['progTempoLoop1']);
$sql.= ", ".($_POST['progInstrucoesLoop1']);
$sql.= ", ".($_POST['progApagouLoop1']);
$sql.= ", ".($_POST['progApagouAllLoop1']);
$sql.= ", ".($_POST['progPlayLoop1']);
$sql.= ", ".($_POST['progLoopLoop1']);
$sql.= ", ".($_POST['progInstrucoesLoopLoop1']);
$sql.= ", ".($_POST['progPulouLoop1']);
$sql.= ", ".($_POST['abstracao']);
$sql.= ", ".($_POST['decomposicao']);
$sql.= ", ".($_POST['reconhecimento']);
$sql.= ", ".($_POST['algoritmo']).")";

$result = mysqli_query($conexao,$sql);
if (mysqli_errno($conexao) > 0) {
    file_put_contents("teste.txt", $sql."\n".mysqli_error($conexao));
    mysqli_close($conexao);
    die();
}
mysqli_close($conexao);
?>