<?php
require "sessao.php";
require "conexao.php";
//Se o teste está sendo feito pela primiera vez para esse estudante nessa amostra
$sql = "select r.idEstudante, ar.* from resultados r, amostras_resultados ar where ar.idResultado = r.idResultado AND r.idEstudante = " . $_SESSION["idUsuario"]. " AND ar.idAmostra=" . $_SESSION["idAmostra"];
require "executaQuery.php";
if (!mysqli_num_rows($result)) {

    //insere o resultado
    $sql = "INSERT INTO resultados ";
    $sql .= "(dataHora, idEstudante, pontosGeral0, pontosDica0, pontosClicks0, pontosTempo0, pontosLimpar0, pontosPulou0, pontosGeral1,pontosDica1, pontosClicks1, pontosTempo1, pontosLimpar1, pontosPulou1, pontosGeral2, pontosDica2, pontosClicks2, pontosTempo2, pontosLimpar2, pontosPulou2, pontosGeral3, pontosDica3, pontosClicks3, pontosTempo3, pontosLimpar3, pontosPulou3, matchGeral0, matchDica0, matchClicks0, matchTempo0, matchGiros0, matchPulou0, matchGeral1, matchDica1, matchClicks1, matchTempo1, matchGiros1, matchPulou1, tangramGeral0, tangramDica0, tangramClicks0, tangramTempo0, tangramGiros0, tangramPulou0, tangramGeral1, tangramDica1, tangramClicks1, tangramTempo1, tangramGiros1, tangramPulou1, classificaGeral,classificaTempo, classificaDica, classificaTentativa, classificaLimpar, classificaPulou, sequenciaGeral0, sequenciaTempo0, sequenciaDica0, sequenciaTentativa0, sequenciaPulou0, sequenciaGeral1, sequenciaTempo1, sequenciaDica1, sequenciaTentativa1, sequenciaPulou1, progGeral0, progTempo0, progInstrucoes0, progApagou0, progApagouAll0, progPlay0, progPulou0, progGeral1, progTempo1, progInstrucoes1, progApagou1, progApagouAll1, progPlay1, progPulou1, progGeral2, progTempo2, progInstrucoes2, progApagou2, progApagouAll2, progPlay2, progPulou2, progGeral3, progTempo3, progInstrucoes3, progApagou3, progApagouAll3, progPlay3, progPulou3, progLoopGeral0, progTempoLoop0, progInstrucoesLoop0, progApagouLoop0, progApagouAllLoop0, progPlayLoop0, progLoopLoop0, progInstrucoesLoopLoop0, progPulouLoop0, progLoopGeral1, progTempoLoop1, progInstrucoesLoop1, progApagouLoop1, progApagouAllLoop1, progPlayLoop1, progLoopLoop1, progInstrucoesLoopLoop1, progPulouLoop1, progLoopGeral2, progTempoLoop2, progInstrucoesLoop2, progApagouLoop2, progApagouAllLoop2, progPlayLoop2, progLoopLoop2, progInstrucoesLoopLoop2, progPulouLoop2, progLoopGeral3, progTempoLoop3, progInstrucoesLoop3, progApagouLoop3, progApagouAllLoop3, progPlayLoop3, progLoopLoop3, progInstrucoesLoopLoop3, progPulouLoop3,  abstracao, decomposicao, reconhecimento, algoritmo) ";
    $sql .= "VALUES ";
    $sql .= "(now()";
    $sql .= ", " . ($_SESSION["idUsuario"]);
    $sql .= ", " . ($_POST['pontosGeral0']);
    $sql .= ", " . ($_POST['pontosDica0']);
    $sql .= ", " . ($_POST['pontosClicks0']);
    $sql .= ", " . ($_POST['pontosTempo0']);
    $sql .= ", " . ($_POST['pontosLimpar0']);
    $sql .= ", " . ($_POST['pontosPulou0']);
    $sql .= ", " . ($_POST['pontosGeral1']);
    $sql .= ", " . ($_POST['pontosDica1']);
    $sql .= ", " . ($_POST['pontosClicks1']);
    $sql .= ", " . ($_POST['pontosTempo1']);
    $sql .= ", " . ($_POST['pontosLimpar1']);
    $sql .= ", " . ($_POST['pontosPulou1']);
    $sql .= ", " . ($_POST['pontosGeral2']);
    $sql .= ", " . ($_POST['pontosDica2']);
    $sql .= ", " . ($_POST['pontosClicks2']);
    $sql .= ", " . ($_POST['pontosTempo2']);
    $sql .= ", " . ($_POST['pontosLimpar2']);
    $sql .= ", " . ($_POST['pontosPulou2']);
    $sql .= ", " . ($_POST['pontosGeral3']);
    $sql .= ", " . ($_POST['pontosDica3']);
    $sql .= ", " . ($_POST['pontosClicks3']);
    $sql .= ", " . ($_POST['pontosTempo3']);
    $sql .= ", " . ($_POST['pontosLimpar3']);
    $sql .= ", " . ($_POST['pontosPulou3']);
    $sql .= ", " . ($_POST['matchGeral0']);
    $sql .= ", " . ($_POST['matchDica0']);
    $sql .= ", " . ($_POST['matchClicks0']);
    $sql .= ", " . ($_POST['matchTempo0']);
    $sql .= ", " . ($_POST['matchGiros0']);
    $sql .= ", " . ($_POST['matchPulou0']);
    $sql .= ", " . ($_POST['matchGeral1']);
    $sql .= ", " . ($_POST['matchDica1']);
    $sql .= ", " . ($_POST['matchClicks1']);
    $sql .= ", " . ($_POST['matchTempo1']);
    $sql .= ", " . ($_POST['matchGiros1']);
    $sql .= ", " . ($_POST['matchPulou1']);
    $sql .= ", " . ($_POST['tangramGeral0']);
    $sql .= ", " . ($_POST['tangramDica0']);
    $sql .= ", " . ($_POST['tangramClicks0']);
    $sql .= ", " . ($_POST['tangramTempo0']);
    $sql .= ", " . ($_POST['tangramGiros0']);
    $sql .= ", " . ($_POST['tangramPulou0']);
    $sql .= ", " . ($_POST['tangramGeral1']);
    $sql .= ", " . ($_POST['tangramDica1']);
    $sql .= ", " . ($_POST['tangramClicks1']);
    $sql .= ", " . ($_POST['tangramTempo1']);
    $sql .= ", " . ($_POST['tangramGiros1']);
    $sql .= ", " . ($_POST['tangramPulou1']);
    $sql .= ", " . ($_POST['classificaGeral']);
    $sql .= ", " . ($_POST['classificaTempo']);
    $sql .= ", " . ($_POST['classificaDica']);
    $sql .= ", " . ($_POST['classificaTentativa']);
    $sql .= ", " . ($_POST['classificaLimpar']);
    $sql .= ", " . ($_POST['classificaPulou']);
    $sql .= ", " . ($_POST['sequenciaGeral0']);
    $sql .= ", " . ($_POST['sequenciaTempo0']);
    $sql .= ", " . ($_POST['sequenciaDica0']);
    $sql .= ", " . ($_POST['sequenciaTentativa0']);
    $sql .= ", " . ($_POST['sequenciaPulou0']);
    $sql .= ", " . ($_POST['sequenciaGeral1']);
    $sql .= ", " . ($_POST['sequenciaTempo1']);
    $sql .= ", " . ($_POST['sequenciaDica1']);
    $sql .= ", " . ($_POST['sequenciaTentativa1']);
    $sql .= ", " . ($_POST['sequenciaPulou1']);
    $sql .= ", " . ($_POST['progGeral0']);
    $sql .= ", " . ($_POST['progTempo0']);
    $sql .= ", " . ($_POST['progInstrucoes0']);
    $sql .= ", " . ($_POST['progApagou0']);
    $sql .= ", " . ($_POST['progApagouAll0']);
    $sql .= ", " . ($_POST['progPlay0']);
    $sql .= ", " . ($_POST['progPulou0']);
    $sql .= ", " . ($_POST['progGeral1']);
    $sql .= ", " . ($_POST['progTempo1']);
    $sql .= ", " . ($_POST['progInstrucoes1']);
    $sql .= ", " . ($_POST['progApagou1']);
    $sql .= ", " . ($_POST['progApagouAll1']);
    $sql .= ", " . ($_POST['progPlay1']);
    $sql .= ", " . ($_POST['progPulou1']);
    $sql .= ", " . ($_POST['progGeral2']);
    $sql .= ", " . ($_POST['progTempo2']);
    $sql .= ", " . ($_POST['progInstrucoes2']);
    $sql .= ", " . ($_POST['progApagou2']);
    $sql .= ", " . ($_POST['progApagouAll2']);
    $sql .= ", " . ($_POST['progPlay2']);
    $sql .= ", " . ($_POST['progPulou2']);
    $sql .= ", " . ($_POST['progGeral3']);
    $sql .= ", " . ($_POST['progTempo3']);
    $sql .= ", " . ($_POST['progInstrucoes3']);
    $sql .= ", " . ($_POST['progApagou3']);
    $sql .= ", " . ($_POST['progApagouAll3']);
    $sql .= ", " . ($_POST['progPlay3']);
    $sql .= ", " . ($_POST['progPulou3']);
    $sql .= ", " . ($_POST['progLoopGeral0']);
    $sql .= ", " . ($_POST['progTempoLoop0']);
    $sql .= ", " . ($_POST['progInstrucoesLoop0']);
    $sql .= ", " . ($_POST['progApagouLoop0']);
    $sql .= ", " . ($_POST['progApagouAllLoop0']);
    $sql .= ", " . ($_POST['progPlayLoop0']);
    $sql .= ", " . ($_POST['progLoopLoop0']);
    $sql .= ", " . ($_POST['progInstrucoesLoopLoop0']);
    $sql .= ", " . ($_POST['progPulouLoop0']);
    $sql .= ", " . ($_POST['progLoopGeral1']);
    $sql .= ", " . ($_POST['progTempoLoop1']);
    $sql .= ", " . ($_POST['progInstrucoesLoop1']);
    $sql .= ", " . ($_POST['progApagouLoop1']);
    $sql .= ", " . ($_POST['progApagouAllLoop1']);
    $sql .= ", " . ($_POST['progPlayLoop1']);
    $sql .= ", " . ($_POST['progLoopLoop1']);
    $sql .= ", " . ($_POST['progInstrucoesLoopLoop1']);
    $sql .= ", " . ($_POST['progPulouLoop1']);
    $sql .= ", " . ($_POST['progLoopGeral2']);
    $sql .= ", " . ($_POST['progTempoLoop2']);
    $sql .= ", " . ($_POST['progInstrucoesLoop2']);
    $sql .= ", " . ($_POST['progApagouLoop2']);
    $sql .= ", " . ($_POST['progApagouAllLoop2']);
    $sql .= ", " . ($_POST['progPlayLoop2']);
    $sql .= ", " . ($_POST['progLoopLoop2']);
    $sql .= ", " . ($_POST['progInstrucoesLoopLoop2']);
    $sql .= ", " . ($_POST['progPulouLoop2']);
    $sql .= ", " . ($_POST['progLoopGeral3']);
    $sql .= ", " . ($_POST['progTempoLoop3']);
    $sql .= ", " . ($_POST['progInstrucoesLoop3']);
    $sql .= ", " . ($_POST['progApagouLoop3']);
    $sql .= ", " . ($_POST['progApagouAllLoop3']);
    $sql .= ", " . ($_POST['progPlayLoop3']);
    $sql .= ", " . ($_POST['progLoopLoop3']);
    $sql .= ", " . ($_POST['progInstrucoesLoopLoop3']);
    $sql .= ", " . ($_POST['progPulouLoop3']);
    $sql .= ", " . ($_POST['abstracao']);
    $sql .= ", " . ($_POST['decomposicao']);
    $sql .= ", " . ($_POST['reconhecimento']);
    $sql .= ", " . ($_POST['algoritmo']) . ")";

}else {
    if(!(isset($_SESSION["idResultado"])) || $_SESSION["idResultado"] == 0) $_SESSION["idResultado"] = mysqli_fetch_array($result)["idResultado"];
    // se o estudante já havia iniciado ou completado o teste dentro dessa amostra, só atualiza a tabela de resultados
    $sql = "UPDATE resultados SET ";
    $sql.='idEstudante ='.$_SESSION["idUsuario"].',';
    $sql.='dataHora = now(),';
    $sql.='pontosGeral0 ='.$_POST['pontosGeral0'].',';
    $sql.='pontosDica0 ='.$_POST['pontosDica0'].',';
    $sql.='pontosClicks0 ='.$_POST['pontosClicks0'].',';
    $sql.='pontosTempo0 ='.$_POST['pontosTempo0'].',';
    $sql.='pontosLimpar0 ='.$_POST['pontosLimpar0'].',';
    $sql.='pontosPulou0 ='.$_POST['pontosPulou0'].',';
    $sql.='pontosGeral1 ='.$_POST['pontosGeral1'].',';
    $sql.='pontosDica1 ='.$_POST['pontosDica1'].',';
    $sql.='pontosClicks1 ='.$_POST['pontosClicks1'].',';
    $sql.='pontosTempo1 ='.$_POST['pontosTempo1'].',';
    $sql.='pontosLimpar1 ='.$_POST['pontosLimpar1'].',';
    $sql.='pontosPulou1 ='.$_POST['pontosPulou1'].',';
    $sql.='pontosGeral2 ='.$_POST['pontosGeral2'].',';
    $sql.='pontosDica2 ='.$_POST['pontosDica2'].',';
    $sql.='pontosClicks2 ='.$_POST['pontosClicks2'].',';
    $sql.='pontosTempo2 ='.$_POST['pontosTempo2'].',';
    $sql.='pontosLimpar2 ='.$_POST['pontosLimpar2'].',';
    $sql.='pontosPulou2 ='.$_POST['pontosPulou2'].',';
    $sql.='pontosGeral3 ='.$_POST['pontosGeral3'].',';
    $sql.='pontosDica3 ='.$_POST['pontosDica3'].',';
    $sql.='pontosClicks3 ='.$_POST['pontosClicks3'].',';
    $sql.='pontosTempo3 ='.$_POST['pontosTempo3'].',';
    $sql.='pontosLimpar3 ='.$_POST['pontosLimpar3'].',';
    $sql.='pontosPulou3 ='.$_POST['pontosPulou3'].',';
    $sql.='matchGeral0 ='.$_POST['matchGeral0'].',';
    $sql.='matchDica0 ='.$_POST['matchDica0'].',';
    $sql.='matchClicks0 ='.$_POST['matchClicks0'].',';
    $sql.='matchTempo0 ='.$_POST['matchTempo0'].',';
    $sql.='matchGiros0 ='.$_POST['matchGiros0'].',';
    $sql.='matchPulou0 ='.$_POST['matchPulou0'].',';
    $sql.='matchGeral1 ='.$_POST['matchGeral1'].',';
    $sql.='matchDica1 ='.$_POST['matchDica1'].',';
    $sql.='matchClicks1 ='.$_POST['matchClicks1'].',';
    $sql.='matchTempo1 ='.$_POST['matchTempo1'].',';
    $sql.='matchGiros1 ='.$_POST['matchGiros1'].',';
    $sql.='matchPulou1 ='.$_POST['matchPulou1'].',';
    $sql.='tangramGeral0 ='.$_POST['tangramGeral0'].',';
    $sql.='tangramDica0 ='.$_POST['tangramDica0'].',';
    $sql.='tangramClicks0 ='.$_POST['tangramClicks0'].',';
    $sql.='tangramTempo0 ='.$_POST['tangramTempo0'].',';
    $sql.='tangramGiros0 ='.$_POST['tangramGiros0'].',';
    $sql.='tangramPulou0 ='.$_POST['tangramPulou0'].',';
    $sql.='tangramGeral1 ='.$_POST['tangramGeral1'].',';
    $sql.='tangramDica1 ='.$_POST['tangramDica1'].',';
    $sql.='tangramClicks1 ='.$_POST['tangramClicks1'].',';
    $sql.='tangramTempo1 ='.$_POST['tangramTempo1'].',';
    $sql.='tangramGiros1 ='.$_POST['tangramGiros1'].',';
    $sql.='tangramPulou1 ='.$_POST['tangramPulou1'].',';
    $sql.='classificaGeral ='.$_POST['classificaGeral'].',';
    $sql.='classificaTempo ='.$_POST['classificaTempo'].',';
    $sql.='classificaDica ='.$_POST['classificaDica'].',';
    $sql.='classificaTentativa ='.$_POST['classificaTentativa'].',';
    $sql.='classificaLimpar ='.$_POST['classificaLimpar'].',';
    $sql.='classificaPulou ='.$_POST['classificaPulou'].',';
    $sql.='sequenciaGeral0 ='.$_POST['sequenciaGeral0'].',';
    $sql.='sequenciaTempo0 ='.$_POST['sequenciaTempo0'].',';
    $sql.='sequenciaDica0 ='.$_POST['sequenciaDica0'].',';
    $sql.='sequenciaTentativa0 ='.$_POST['sequenciaTentativa0'].',';
    $sql.='sequenciaPulou0 ='.$_POST['sequenciaPulou0'].',';
    $sql.='sequenciaGeral1 ='.$_POST['sequenciaGeral1'].',';
    $sql.='sequenciaTempo1 ='.$_POST['sequenciaTempo1'].',';
    $sql.='sequenciaDica1 ='.$_POST['sequenciaDica1'].',';
    $sql.='sequenciaTentativa1 ='.$_POST['sequenciaTentativa1'].',';
    $sql.='sequenciaPulou1 ='.$_POST['sequenciaPulou1'].',';
    $sql.='progGeral0 ='.$_POST['progGeral0'].',';
    $sql.='progTempo0 ='.$_POST['progTempo0'].',';
    $sql.='progInstrucoes0 ='.$_POST['progInstrucoes0'].',';
    $sql.='progApagou0 ='.$_POST['progApagou0'].',';
    $sql.='progApagouAll0 ='.$_POST['progApagouAll0'].',';
    $sql.='progPlay0 ='.$_POST['progPlay0'].',';
    $sql.='progPulou0 ='.$_POST['progPulou0'].',';
    $sql.='progGeral1 ='.$_POST['progGeral1'].',';
    $sql.='progTempo1 ='.$_POST['progTempo1'].',';
    $sql.='progInstrucoes1 ='.$_POST['progInstrucoes1'].',';
    $sql.='progApagou1 ='.$_POST['progApagou1'].',';
    $sql.='progApagouAll1 ='.$_POST['progApagouAll1'].',';
    $sql.='progPlay1 ='.$_POST['progPlay1'].',';
    $sql.='progPulou1 ='.$_POST['progPulou1'].',';
    $sql.='progGeral2 ='.$_POST['progGeral2'].',';
    $sql.='progTempo2 ='.$_POST['progTempo2'].',';
    $sql.='progInstrucoes2 ='.$_POST['progInstrucoes2'].',';
    $sql.='progApagou2 ='.$_POST['progApagou2'].',';
    $sql.='progApagouAll2 ='.$_POST['progApagouAll2'].',';
    $sql.='progPlay2 ='.$_POST['progPlay2'].',';
    $sql.='progPulou2 ='.$_POST['progPulou2'].',';
    $sql.='progGeral3 ='.$_POST['progGeral3'].',';
    $sql.='progTempo3 ='.$_POST['progTempo3'].',';
    $sql.='progInstrucoes3 ='.$_POST['progInstrucoes3'].',';
    $sql.='progApagou3 ='.$_POST['progApagou3'].',';
    $sql.='progApagouAll3 ='.$_POST['progApagouAll3'].',';
    $sql.='progPlay3 ='.$_POST['progPlay3'].',';
    $sql.='progPulou3 ='.$_POST['progPulou3'].',';
    $sql.='progLoopGeral0 ='.$_POST['progLoopGeral0'].',';
    $sql.='progTempoLoop0 ='.$_POST['progTempoLoop0'].',';
    $sql.='progInstrucoesLoop0 ='.$_POST['progInstrucoesLoop0'].',';
    $sql.='progApagouLoop0 ='.$_POST['progApagouLoop0'].',';
    $sql.='progApagouAllLoop0 ='.$_POST['progApagouAllLoop0'].',';
    $sql.='progPlayLoop0 ='.$_POST['progPlayLoop0'].',';
    $sql.='progLoopLoop0 ='.$_POST['progLoopLoop0'].',';
    $sql.='progInstrucoesLoopLoop0 ='.$_POST['progInstrucoesLoopLoop0'].',';
    $sql.='progPulouLoop0 ='.$_POST['progPulouLoop0'].',';
    $sql.='progLoopGeral1 ='.$_POST['progLoopGeral1'].',';
    $sql.='progTempoLoop1 ='.$_POST['progTempoLoop1'].',';
    $sql.='progInstrucoesLoop1 ='.$_POST['progInstrucoesLoop1'].',';
    $sql.='progApagouLoop1 ='.$_POST['progApagouLoop1'].',';
    $sql.='progApagouAllLoop1 ='.$_POST['progApagouAllLoop1'].',';
    $sql.='progPlayLoop1 ='.$_POST['progPlayLoop1'].',';
    $sql.='progLoopLoop1 ='.$_POST['progLoopLoop1'].',';
    $sql.='progInstrucoesLoopLoop1 ='.$_POST['progInstrucoesLoopLoop1'].',';
    $sql.='progPulouLoop1 ='.$_POST['progPulouLoop1'].',';
    $sql.='progLoopGeral2 ='.$_POST['progLoopGeral2'].',';
    $sql.='progTempoLoop2 ='.$_POST['progTempoLoop2'].',';
    $sql.='progInstrucoesLoop2 ='.$_POST['progInstrucoesLoop2'].',';
    $sql.='progApagouLoop2 ='.$_POST['progApagouLoop2'].',';
    $sql.='progApagouAllLoop2 ='.$_POST['progApagouAllLoop2'].',';
    $sql.='progPlayLoop2 ='.$_POST['progPlayLoop2'].',';
    $sql.='progLoopLoop2 ='.$_POST['progLoopLoop2'].',';
    $sql.='progInstrucoesLoopLoop2 ='.$_POST['progInstrucoesLoopLoop2'].',';
    $sql.='progPulouLoop2 ='.$_POST['progPulouLoop2'].',';
    $sql.='progLoopGeral3 ='.$_POST['progLoopGeral3'].',';
    $sql.='progTempoLoop3 ='.$_POST['progTempoLoop3'].',';
    $sql.='progInstrucoesLoop3 ='.$_POST['progInstrucoesLoop3'].',';
    $sql.='progApagouLoop3 ='.$_POST['progApagouLoop3'].',';
    $sql.='progApagouAllLoop3 ='.$_POST['progApagouAllLoop3'].',';
    $sql.='progPlayLoop3 ='.$_POST['progPlayLoop3'].',';
    $sql.='progLoopLoop3 ='.$_POST['progLoopLoop3'].',';
    $sql.='progInstrucoesLoopLoop3 ='.$_POST['progInstrucoesLoopLoop3'].',';
    $sql.='progPulouLoop3 ='.$_POST['progPulouLoop3'].',';
    $sql.='abstracao ='.$_POST['abstracao'].',';
    $sql.='decomposicao ='.$_POST['decomposicao'].',';
    $sql.='reconhecimento ='.$_POST['reconhecimento'].',';
    $sql.='algoritmo ='.$_POST['algoritmo'];
    $sql.=' WHERE idResultado = '.$_SESSION["idResultado"];
}
file_put_contents("sql.txt", $sql);

require "executaQuery.php";

// Agora precisa atualizar a tabela de cruzamento de resultados e amostras para identificar
// que esse usuario já fez o teste nessa amostra
// se ele não tinha ID de resultado antes, ou seja, se foi inserido agora
if($_SESSION["idResultado"]==0) {
    //pega o id inserido e pesquisa pra ter certeza de que esse id é do usuario que acabou de fazer o teste
    $insertId = mysqli_insert_id($conexao);
    $sql = "SELECT idEstudante FROM resultados WHERE idResultado = $insertId";
    require "executaQuery.php";
    if (mysqli_num_rows($result) > 0) {
        $resultado = mysqli_fetch_array($result);
        //se o id do usuário inserido confere com esse estudante
        if ($resultado["idEstudante"] == $_SESSION["idUsuario"]) {
            $sql = "INSERT INTO amostras_resultados (idAmostra, idResultado) VALUES (" . $_SESSION["idAmostra"] . ",$insertId)";
            require "executaQuery.php";
        }
    }
}
mysqli_close($conexao);
?>